### ISSUE TITLE
ANT cannot be installed with User permissions

### ISSUE THREAD

**Issue by bkolbCSO** [dgalbraith/chocolatey-packages#200]
I try to install ant with user permissions. This does not work. I am stuck in the extracting phase. My suspicion is that the problem is ANT_HOME with is supposed to be set to Machine

**Comment by dgalbraith** [comment]
The standard approach for chocolatey packages is to require admin-level access and install packages at the machine level.  The current approach to the package reflected this.

Are you trying to install in an environment where you do not have admin access available?

**Comment by bkolbCSO** [comment]
Yes, exactly. I followed the setup instructions for choco without admin rights. In most cases it works, but for this package it does not. Maybe it would be possible to add an parameter with which I could influence the user install?

**Comment by dgalbraith** [comment]
I have added a 'User' parameter to the package which supports installing the ANT_HOME environment variable at the user level rather than the machine level to support this - choco install -y ant --params='/User'.

The package has been updated and the change will be available with the ANT 1.10.10 version which has just been released by the ASF.
