### ISSUE TITLE
Amend ssrs-2019 automatic updater to deal with new versioning on distribution page

### ISSUE THREAD

**Issue by dgalbraith** [dgalbraith/chocolatey-packages#289]
The versioning on the distribution page for Sql Server Reporting Services has been modified to use
the product version rather than the file version as was the case previously. 

Packages were previously versioned using the published file version so the updater needs to be amended
to be able to map between the old and new versioning schemes.

**Comment by christhebatchelor** [comment]
Is this something that you still intend to resolve? It still appears to be broken and it has been quite a while so I fear maybe you've moved on.

**Comment by dgalbraith** [comment]
To be honest I was unable to find a good solution on this one - changing the versioning scheme used for the product mid flight was a less than ideal choice by Microsoft.  The new versioning scheme for the product/download page moved to versioning that was < the version which had already been pubished.

I can see that there is a new version - I will update the package and push the latest.  Current product version is 15.0.1102.1084 which represents 15.0.8559.29221.

**Comment by christhebatchelor** [comment]
That's unfortunate, but I really appreciate the quick response here. I wish I had a better grasp of creating chocolatey packages to lend more of a hand. This creates a bit of an issue orchestrating this install via Salt, so currently trying to find a workaround there... It seems trying to fit Windows into a DevOps world will never cease to be frustrating.

(Not really your problem but just explaining anyway) Currently, the checksum seems to be mismatched for this package, which causes an issue in Salt since they haven't seen fit to open up the capability to override the package checksum manually:
https://github.com/saltstack/salt/issues/38331

For now, I'm trying to just run the choco commands directly rather than going through a salt state and hoping that works better, but still working on testing for that.

**Comment by dgalbraith** [comment]
@christhebatchelor I have updated the [package](https://community.chocolatey.org/packages/ssrs-2019/15.0.8559.29221) to reflect the latest release / hashes by Microsoft.  This is still subject to moderation so you can wait for that process to complete and install with ```choco install ssrs-2019``` or if the need is immediate you can override and install the specific version ```choco install ssrs-2019 --version=15.0.8559.29221``` although I suspect that will be subject to the issue referenced above with no way to pass the version override using Salt.

**Comment by dgalbraith** [comment]
@christhebatchelor Latest versions are now available - [ssrs-2019 15.0.8559.29221](https://community.chocolatey.org/packages/ssrs-2019/15.0.8559.29221).  This represents the current 15.0.1102.1084 product available from Microsoft.

The delta in the versioning of the Chocolatey package versus the Microsoft product version is because Microsoft switched version schemes - they used to publish under the file version which is what the package uses, but switched to using a product version with versions lower than those already used/published for the file version.

Given this I have continued with the file version scheme but have not come up with a good solution to automate this.  Please feel free to let me know if the package goes out of sync again and I can update.
