### ISSUE TITLE
All Nheko upgrades fail with installer error

### ISSUE THREAD

**Issue by opusforlife2** [dgalbraith/chocolatey-packages#363]
~~Hi. I can see that Nheko version 0.9.1 has passed automatic review and is stuck waiting for mod approval. Is this step bound to take time? Or could you maybe ping a mod to take a look at it?~~

Nheko 0.9.1 is available for upgrade, but the installer fails with an error. Could you please check this?

**Comment by opusforlife2** [comment]
All Nheko upgrades fail with an installer error. I have to uninstall and reinstall it each and every time.

**Comment by dgalbraith** [comment]
@opusforlife2 I will take a look at the package and see if I can determine what is happening.

Given the Chocolatey script is just a wrapper it could well be an issue with the underlying installer - will review.

**Comment by opusforlife2** [comment]
Any luck with debugging this? Just tried to upgrade to 0.10.0 and it still fails.

**Comment by dgalbraith** [comment]
This appears to be an issue with the package installer - it fails to install if the target directory already exists.

This is however compounded by the package binaries not being uninstalled by Chocolatey on package removal so any upgrade or install will fail if the package has been previously installed on the host.

The Chocolatey automatic uninstall functionality does not seem to work with Qt5 installers.

Additional investigation required but it should be possible to write an explicit uninstall function for the package which will ensure removal.

In the interim the only work-around that I can think of is to remove a prior version through the Windows Add/Remove functionality or running the `maintenancetool.exe` from the package install directory to remove the installation prior to an update/new install using the Chocolatey package.

**Comment by opusforlife2** [comment]
> This appears to be an issue with the package installer - it fails to install if the target directory already exists.

Would it be worth pinging the nheko maintainer to see if this can be fixed?

**Comment by dgalbraith** [comment]
The installer is slightly non-standard but appears to broadly function as expected if executed manually so not sure that there is something for the maintainers to fix.  Running the installer manually successfully detects the prior install and prompts for the directory to be deleted.

I think the real problem lies with Chocolatey not correctly handling an uninstall of a Qt installer - the installer is not detected/backed out by the automatic uninstall process so when the package is uninstalled the install directory and contents remain.  This means that subsequent upgrades/installs fail.

I have addressed by suppressing the automatic uninstaller and implementing specific handling to invoke the package removal/uninstall using the mechanism provided by the Qt installers - `maintenancetool.exe`.

Installs/upgrades going forward should be good but it will likely be necessary to manually uninstall or remove the `C:\Program Files (x86)\nheko` directory prior to the first install/upgrade.  Once there has been a successful install of 0.10.1.20220909 or later package upgrades and removal will succeed.

**Comment by opusforlife2** [comment]
Alright, I'll do that. Thank you so much!

**Comment by opusforlife2** [comment]
Hi. Tried to install 0.10.2 over 0.10.1.20220910 today. It failed, and then nheko vanished from Choco GUI's installed list.
