### ISSUE TITLE
(fluidsynth) Old files left behind after package upgrade

### ISSUE THREAD

**Issue by opusforlife2** [dgalbraith/chocolatey-packages#399]
Hi. Some files from previous versions are lying around in the `lib > fluidsynth` folder, like:

```
fluidsynth-2.2.3-win10-x64.zip.txt
fluidsynth-2.2.4-win10-x64.zip.txt
fluidsynth-2.2.5-win10-x64.zip.txt
```

and so on. Is it possible to ensure these are deleted when the package is upgraded?

**Comment by dgalbraith** [comment]
These files are the zip content files from the Chocolatey install - the function `Get-ChocolateyUnzip` creates these files to record the files that have been extracted from the archive.

It seems like the proper behavior for the package should be to unwind the install by invoking the  helper function `Uninstall-ChocolateyZipPackage ` to remove all of the files that were added/installed with the package.  When this function is invoked the contents previously extracted from the archive are removed along with the zip content files.

The package should be updated to provide an uninstaller (`chocolateyUninstall.ps1`) that invokes this helper function to ensure ful cleanup on upgrade/removal.  Package files should probably also be extracted to a known location such as `$env:ChocolateyToolsLocation` rather than being left in the Chocolatey package folder given `include` and `lib` directories are shipped with the package - it seems better for these to be in a standard location rather than being subject to change on a per-release basis.

**Comment by opusforlife2** [comment]
I just remembered I had opened a bunch of these issues based on the same problem. One response I got [here](https://github.com/pauby/ChocoPackages/issues/134#issuecomment-1106805194) was:

> Those belong to Chocolatey so they need to be left alone.

That's not the case, right, since you've found a proper way to remove these?

**Comment by dgalbraith** [comment]
@optusforlife2 it is true that these files are internal files used by Chocolatey.

When a package uses the helper function `Install-ChocolateyZipPackage`/`Get-ChocolateyUnzip` to extract files from an archive these files are generated - they indicate the files which have been extracted from the archive.  These content files are used by `Uninstall-ChocolateyZipPackage` to remove any files which have been extracted/installed this way.

What `Uninstall-ChocolateyZipPackage` does not do however is delete these contents files themselves - only the extracted files which they reference.

My view on this is that these are safe to remove if they have been handled correctly i.e any contents extracted from the archive removed.  Given the way that Chocolatey functions there are 2 ways that I see this happening:

1. Update handling in `Uninstall-ChocolateyZipPackage`  to remove these contents files post processing; or
2. Add handling in applicable packages (those where `Install-ChocolateyZipPackage`/`Get-ChocolateyUnzip` have been used) with a chocolateyBeforeModify.ps1 which calls the `Uninstall-ChocolateyZipPackage` function using the content file and then removes the content file

A good example of this is probably against another of your [issues](https://github.com/mkevenaar/chocolatey-packages/issues/125) covering this behavior for [exiftool](https://github.com/mkevenaar/chocolatey-packages/tree/master/automatic/exiftool).

Looking at my update for fluidsynth I think I need to shift the handling - I put it in `chocolateyUninstall.ps1` instead of `chocoateyBeforeModify.ps1`!

**Comment by opusforlife2** [comment]
But you'd only need the latest txt file matching the package version, no? So there should only be one txt file there, not an arbitrary number of them from whatever previous versions you ever used.

It's fairly innocuous, but it's also a small privacy violation in a way, since someone can tell what versions of that software you used in the past.

**Comment by dgalbraith** [comment]
You only need the latest text file matching the package version provided the package upgrades are successfully removing the old files.  To do so is not straightforward/immediately obvious and requires proper removal in `chocolateyBeforeModify.ps1`.  Not sure if this is actually recommended though, and certainly not something you see in the vast majority of packages.

When there is a call to [`UnInstall-ChocolateyZipPackage.ps1`](https://github.com/chocolatey/choco/blob/develop/src/chocolatey.resources/helpers/functions/UnInstall-ChocolateyZipPackage.ps1) any contents files in the directory are processed thus removing the extracted files for that version.

```posh
  # The Zip Content File may have previously existed under a different
  # name.  If *Install.txt doesn't exist, check for the old name
  if(-Not (Test-Path -Path $zipContentFile)) {
    $zipContentFile=(Join-Path $packagelibPath -ChildPath $zipFileName) + ".txt"
  }

  if ((Test-Path -path $zipContentFile)) {
    $zipContentFile
    $zipContents=get-content $zipContentFile
    foreach ($fileInZip in $zipContents) {
      if ($fileInZip -ne $null -and $fileInZip.Trim() -ne '') {
        Remove-Item -Path "$fileInZip" -ErrorAction SilentlyContinue -Recurse -Force
      }
    }
  }
```

When a package is removed anything beneath the `Chocolatey\lib\[package]` hierarchy is removed in any case so it really seems to come down to a question of now or later  the interim implication of a visible version history for those applications/packages which update without an interim removal.

**Comment by opusforlife2** [comment]
I suppose the most appropriate place to address this would be in choco itself, since applying custom handling in every package is infeasible?

**Comment by opusforlife2** [comment]
Ah, sure. Since this is in dgalbraith's fork, I thought no one else would be disturbed. My bad.

**Comment by pauby** [comment]
Jeez. So it is. @dgalbraith I am sorry. I didn't notice this was your repository and I've come in with my size 10's and walked all over it. My sincere apologies.

If you want to discuss the change to Chocolatey then the discussion would be the best place.

I'll walk away now sheepishly.

**Comment by dgalbraith** [comment]
@pauby not an issue! I must also confess to some culpability - I tagged you in one of my responses which may well have clouded things.

I have been looking for somewhere to kick that discussion off and the [Discussions](https://github.com/chocolatey/choco/discussions) seem like an excellent place for this - thanks!

**Comment by opusforlife2** [comment]
@dgalbraith Please tag me when you do so that I can follow it.
