### ISSUE TITLE
watchman outdated

### ISSUE THREAD

**Issue by Araxeus** [dgalbraith/chocolatey-packages#451]
https://github.com/dgalbraith/chocolatey-packages/tree/master/automatic/watchman
https://github.com/facebook/watchman/releases

**Comment by dgalbraith** [comment]
@Araxeus thanks for flagging.

Package updates were broken due to a structural change around release artifacts on the GitHub site.

Artifact determination for GitHub releases has been broken out into utility methods which are able to
correctly handle the new structures and the package build should be correct moving forward.
