### ISSUE TITLE
OpenVPN - Issue with PLAP(Pre-Login Access Provider) option

### ISSUE THREAD

**Issue by rog9876** [dgalbraith/chocolatey-packages#517]
Hi,

I posted this on chocolatey already but not sure if this may be the better place.

/PLAP parameter does not appear to work correctly.

```
DEBUG: Error 2711: The specified Feature name ('OpenVPN.PLAP') not found in Feature Table.
MSI (s) (F4:3C) [09:36:21:423]: Product: OpenVPN 2.6.7-I001 amd64 -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2711. The arguments are: OpenVPN.PLAP, ,
```

Thanks
Rog

**Comment by Lun4r161** [comment]
I Think the Problem is the /Plap parameter in the chocolateyInstall.ps1.
OLD: 
'PLAP' {
	      Write-Verbose('Pre-Logon Access-Provider will be activated')
	      $local += 'OpenVPN.PLAP'

NEW: 
'PLAP' {
	      Write-Verbose('Pre-Logon Access-Provider will be activated')
	      $local += 'OpenVPN.PLAP.Register'

Because if install it from hand the logs show this parameters:
`Adding ADDLOCAL property. Its value is 'OpenVPN.GUI,OpenVPN.Service,OpenVPN.Documentation,OpenVPN.SampleCfg,Drivers.OvpnDco,OpenSSL,OpenVPN,OpenVPN.GUI.OnLogon,OpenVPN.PLAP.Register,Drivers,Drivers.TAPWindows6,Drivers.Wintun'`

**Comment by rog9876** [comment]
Hi all,

Thank you for looking at this and identifying the issue. I am however still getting the same error when installing using below.

`choco install openvpn --params="/TapDriver /Gui /PLAP"`

**Comment by Lun4r161** [comment]
New Issue opened:
https://github.com/dgalbraith/chocolatey-packages/issues/524

**Comment by dgalbraith** [comment]
@rog9876 @Lun4r161 Updated handling for the PLAP parameter is now available with the package in the community repository - versions ``` 2.6.9.001``` and greater.
